version: '3.8'
services:
  db:
    image: mariadb:11.3.2
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    volumes:
      - ./data_base:/var/lib/mysql
    networks:
      - backend
      
  bff:
    image: lingatsu/backend:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    env_file:
      - .env
    networks:
      - backend
      
  front:
    image: lingatsu/frontend
    ports:
      - 4200:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend

networks:
  backend:
  frontend: