version: '3.8'
services:
  db:
    image: mariadb:11.3.2
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=${USER}
    #   - MYSQL_DATABASE=docker
    #   - MYSQL_USER=${USER}
    #   - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - ./data_base:/var/lib/mysql
    networks:
      - backend

      
  bff:
    image: lingatsu/backend:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    # environment:
    #   - DB_USERNAME=${USER}
    #   - DB_PASSWORD=${PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    # restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    networks:
      - backend
      
  front:
    image: lingatsu/frontend
    ports:
      - 4200:80
    environment:
      - BFF_URL=http://bff:80
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: